server:
  port: 8081    # choose an unused port (product, order, etc., might already use others)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stream_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: numpy@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: stream-service

# Eureka Client (for service discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logging (optional)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/stream-service.log

# Agora Config
agora:
  app-id: YOUR_AGORA_APP_ID
  app-certificate: YOUR_AGORA_APP_CERTIFICATE
  token-expiry-seconds: 3600
