# server:
#   port: 8082

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/live_commerce
#     username: postgres
#     password: root

#   jpa:
#     hibernate:
#       ddl-auto: update
#     open-in-view: false

#   liquibase:
#     change-log: classpath:db/changelog/db.changelog-master.yml

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_commerce_product?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: numpy@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

management:
  endpoints:
    web:
      exposure:
        include: health,info
